[project]
name = "torchTextClassifiers"
description = "An implementation of the https://github.com/facebookresearch/fastText supervised learning algorithm for text classification using Pytorch."
authors = [
    { name = "Tom Seimandi", email = "tom.seimandi@gmail.com" },
    { name = "Julien Pramil", email = "julien.pramil@insee.fr" },
    { name = "Meilame Tayebjee", email = "meilame.tayebjee@insee.fr" },
    { name = "Cédric Couralet", email = "cedric.couralet@insee.fr" },
]
readme = "README.md"
repository = "https://github.com/InseeFrLab/torch-fastText"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = ["fastText", "text classification", "NLP", "automatic coding", "deep learning"]
dependencies = [
    "numpy>=1.26.4",
    "pytorch-lightning>=2.4.0"
]
requires-python = ">=3.11"
version="0.0.0-dev"


[dependency-groups]
dev = [
  "pytest >=8.1.1,<9"
]

[project.optional-dependencies]
explainability = ["unidecode", "nltk", "captum"]
preprocess =     ["unidecode", "nltk"]

[build-system]
requires = ["uv_build>=0.7.8,<0.8.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 100


[tool.uv.build-backend]
module-name="torchTextClassifiers"
module-root = ""



